# Generated by Django 4.2.16 on 2025-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(blank=True, choices=[('request', 'ご依頼'), ('consultation', 'ご相談'), ('inquiry', 'お問い合わせ'), ('other', 'その他')], default='other', max_length=30, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='お問い合わせ内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100, verbose_name='お名前'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='電話番号'),
        ),
    ]
