# Generated by Django 4.2.16 on 2025-01-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_items', to='about.aboutmaincategory')),
            ],
        ),
    ]
