# Generated by Django 5.1.3 on 2024-11-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique_for_date='published_date', verbose_name='スラッグ'),
        ),
    ]
