# Generated by Django 4.2.16 on 2025-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='会社名')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=100, verbose_name='電話番号')),
                ('category', models.CharField(blank=True, choices=[('request', 'ご依頼'), ('consultation', 'ご相談'), ('inquiry', 'お問い合わせ'), ('other', 'その他')], default='other', max_length=30, verbose_name='カテゴリ')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
