# Generated by Django 4.2.16 on 2025-01-13 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
                ('title_ja', models.CharField(max_length=100, verbose_name='日本語名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'メインカテゴリー',
                'verbose_name_plural': 'メインカテゴリー',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
                ('title_ja', models.CharField(max_length=100, verbose_name='日本語名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='about.maincategory', verbose_name='メインカテゴリー')),
            ],
            options={
                'verbose_name': 'サブカテゴリー',
                'verbose_name_plural': 'サブカテゴリー',
                'ordering': ['main_category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='about.subcategory', verbose_name='サブカテゴリー')),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
                'ordering': ['sub_category', 'order'],
            },
        ),
    ]
