# Generated by Django 5.1.5 on 2025-02-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmaincategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='aboutmaincategory',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='アイコン'),
        ),
    ]
